### ISSUE TITLE
Error building example clientset: No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by maguro** [openshift-evangelists/crd-code-generation#7]
I run

    $ ./example -kubeconfig ~/.kube/config

and I get

```
F0510 12:14:20.618026   25427 main.go:30] Error building example clientset: No Auth Provider found for name "gcp"
goroutine 1 [running]:
github.com/openshift-evangelists/crd-code-generation/vendor/github.com/golang/glog.stacks(0xc4203d4e00, 0xc420218000, 0x72, 0xc7)
	/Users/acabrera/go/src/github.com/openshift-evangelists/crd-code-generation/vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/openshift-evangelists/crd-code-generation/vendor/github.com/golang/glog.(*loggingT).output(0x21da2c0, 0xc400000003, 0xc4200ee630, 0x216c8b4, 0x7, 0x1e, 0x0)
	/Users/acabrera/go/src/github.com/openshift-evangelists/crd-code-generation/vendor/github.com/golang/glog/glog.go:720 +0x32d
github.com/openshift-evangelists/crd-code-generation/vendor/github.com/golang/glog.(*loggingT).printf(0x21da2c0, 0x3, 0x1aff178, 0x24, 0xc420487cd8, 0x1, 0x1)
	/Users/acabrera/go/src/github.com/openshift-evangelists/crd-code-generation/vendor/github.com/golang/glog/glog.go:655 +0x14b
github.com/openshift-evangelists/crd-code-generation/vendor/github.com/golang/glog.Fatalf(0x1aff178, 0x24, 0xc420487cd8, 0x1, 0x1)
	/Users/acabrera/go/src/github.com/openshift-evangelists/crd-code-generation/vendor/github.com/golang/glog/glog.go:1148 +0x67
main.main()
	/Users/acabrera/go/src/github.com/openshift-evangelists/crd-code-generation/cmd/example/main.go:30 +0x166
```

**Comment by sttts** [comment]
For GKE clusters you need this import: https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go#L32

**Comment by maguro** [comment]
Thanks!
